const fs = require('fs');

const path = './public/data/library_guides.json';
const data = JSON.parse(fs.readFileSync(path, 'utf8'));

const guide = data.guides.find(g => g.id === "guide_nasil_galerici_olunur");

if (guide) {
  // Keep the first 10 steps (or existing steps) but we will append the new ones.
  // We'll keep the current guide.sections and just push to it.
  
  // First, to avoid duplicates if this script is run twice, remove steps > 10.
  const baseSections = guide.sections.filter(s => {
    if (s.type === 'intro') return true;
    if (s.title) {
        const match = s.title.match(/Adım (\d+)/);
        if (match && parseInt(match[1]) <= 10) return true;
    }
    return false;
  });

  const newSteps = [
    {
      "type": "step",
      "title": "Adım 11: Sektörel Arka Plan ve Kurumsallaşma Vizyonu",
      "content": "İkinci el motorlu kara taşıtı ticareti, modern ekonomilerde otomotiv perakendeciliğinin en dinamik, en yüksek işlem hacmine sahip ve çarpan etkisi en geniş alt sektörlerinden birini temsil etmektedir. Türkiye makroekonomik konjonktürü içerisinde değerlendirildiğinde, otomobillerin salt bir ulaşım aracı olma vasfından çıkarak, yüksek enflasyonist dönemlerde değer koruma ve yatırım aracına dönüşmesi, bu sektöre yönelik ilgiyi ve sermaye akışını eksponansiyel biçimde artırmıştır. Geçmiş yıllarda 'ayaklı galericilik' olarak tabir edilen, herhangi bir mesleki yeterliliğe, fiziki standarda veya mali sorumluluğa dayanmayan kayıt dışı alım-satım işlemleri, piyasada ciddi asimetrik bilgi problemlerine, vergi kayıplarına ve tüketici mağduriyetlerine yol açmıştır.\n\nBu yapısal sorunların çözümü, haksız rekabetin ortadan kaldırılması ve sektörün tamamen kurumsal bir ekosisteme entegre edilmesi amacıyla Ticaret Bakanlığı, Çevre ve Şehircilik Bakanlığı ile İçişleri Bakanlığı koordinasyonunda devasa bir hukuki regülasyon süreci başlatılmıştır. İkinci El Motorlu Kara Taşıtlarının Ticareti Hakkında Yönetmelik ve İşyeri Açma ve Çalışma Ruhsatlarına İlişkin Yönetmelik ekseninde şekillenen bu yeni dönem, oto galeri işletmeciliğini vizyonsuz bir ticari faaliyet olmaktan çıkarıp, çok sıkı denetim mekanizmalarına, yüksek asgari sermaye gereksinimlerine ve ağır yasal garanti sorumluluklarına sahip saygın bir kurumsal finansal perakendecilik modeline dönüştürmüştür. Günümüzde yasal ve tam yetkili bir ikinci el motorlu kara taşıtı ticareti işletmesi kurmak; imar hukukundan iş sağlığı ve güvenliğine, bankacılık regülasyonlarından tüketici haklarına kadar uzanan geniş bir yelpazede multidisipliner bir uyum sürecini zorunlu kılmaktadır."
    },
    {
      "type": "step",
      "title": "Adım 12: Hukuki Statü Seçimi ve Şirket Türleri Regülasyonları",
      "content": "İkinci el motorlu kara taşıtı ticaretine giriş yapacak bir müteşebbisin veya yatırımcı grubunun atması gereken ilk stratejik adım, işletmenin hukuki statüsünün belirlenmesidir. Ticari faaliyetler şahıs işletmesi statüsünde yürütülebilse de, sektörün barındırdığı yüksek finansal riskler, araç envanterinin gerektirdiği devasa nakit akışı ve ticari kredibilitenin tesisi açısından sermaye şirketleri (Limited Şirket veya Anonim Şirket) açık ara en rasyonel tercih olarak öne çıkmaktadır.",
      "subsections": [
        {
          "subtitle": "Asgari Sermaye Regülasyonları (50.000 TL - 500.000 TL)",
          "text": "Ticaret Bakanlığı İç Ticaret Genel Müdürlüğü tarafından yayımlanan ve 1 Ocak 2024 tarihinden itibaren geçerli olan güncel mevzuat düzenlemeleri ile sermaye şirketlerinin kuruluş aşamasındaki asgari özkaynak gereksinimleri radikal bir biçimde artırılmıştır. Resmi Gazete'de yayımlanan 7887 Sayılı Karar uyarınca, yeni kurulacak limited şirketler (Ltd. Şti.) için asgari sermaye tutarı 50.000 Türk Lirasına yükseltilmiştir. Kurumsal yönetişim ilkelerinin daha katı uygulandığı, pay devirlerinin daha esnek olduğu anonim şirketler (A.Ş.) söz konusu olduğunda ise, başlangıç sermayesi alt sınırı 50.000 TL'den 250.000 TL'ye çıkarılmış; kayıtlı sermaye sistemini kabul etmiş bulunan ve halka açık olmayan anonim şirketler için başlangıç sermayesi ile çıkarılmış sermaye tutarının alt limiti 500.000 Türk Lirasına sabitlenmiştir.\n\nSöz konusu asgari sermaye artırımları, kağıt üzerinde kurulan tabela şirketlerinin ve finansal derinliği olmayan spekülatif aktörlerin piyasaya girişini engellemeyi amaçlayan makro ihtiyati bir tedbirdir. Sermayesi belirtilen yeni yasal limitlerin altında kalan ve daha önceden kurulmuş mevcut şirketler için bu aşamada zorunlu bir intibak ve sermaye artırımı öngörülmemiş olmakla birlikte, enflasyonist ortamda özkaynak yapılarının güçlü tutulması ve ticari bankalar nezdindeki kredi limit tahsislerinin sorunsuz ilerleyebilmesi adına, sermaye artırımı yapılması Ticaret Bakanlığı tarafından özellikle tavsiye edilmektedir."
        },
        {
          "subtitle": "Oda Kayıt ve Tescil İşlemleri",
          "text": "Şirket ana sözleşmesinin tescil ve ilan edilmesi, vergi levhasının alınması işlemlerinin akabinde, yetki belgesi sürecinin başlatılabilmesi için işletmenin faaliyet gösterdiği ildeki ilgili meslek odasına kayıt yaptırması yasal bir mecburiyettir. İşletme sahipleri, ticaretin hacmine ve şirket türüne göre bulundukları ilin Ticaret Odasına veya Esnaf ve Sanatkarlar Odasına müracaat etmelidir. Örneğin, bu faaliyetin yoğun bir şekilde yürütüldüğü İzmir ilinde, yatırımcılar İzmir Ticaret Odası bünyesindeki ilgili meslek komitesine kayıt olabilecekleri gibi, İzmir Şoförler ve Otomobilciler Esnaf Odası ile doğrudan entegre çalışan İzmir Oto Galericiler, Müşavirlik, Kiralama ve Yıkamacılar Esnaf Odası'na da kayıt gerçekleştirebilmektedirler. Bu odalardan temin edilecek 'Oda Kayıt Belgesi', tüm bürokratik serüvenin temel taşı niteliğindedir."
        }
      ]
    },
    {
      "type": "step",
      "title": "Adım 13: Gayrimenkul Seçimi, İmar Hukuku ve Fiziki Standartlar",
      "content": "Oto galeri açılış süreçlerinde yatırımcıların karşılaştığı en yoğun bürokratik filtreleme, işletmenin kurulacağı gayrimenkulün imar durumu ve fiziki kapasitesi üzerinedir. Geçmiş yıllarda apartman altlarında, dar sokaklarda faaliyet gösteren galerilerin yarattığı otopark krizleri, egzoz emisyonları, yangın riskleri ve gürültü kirliliği, yasa koyucuyu şehir planlaması bağlamında son derece katı kararlar almaya itmiştir. Çevre, Şehircilik ve İklim Değişikliği Bakanlığı'nın yayımladığı genelgeler doğrultusunda, oto galerilerin yer seçimi sıfırdan ve kesin kurallarla yeniden düzenlenmiştir.",
      "subsections": [
        {
          "subtitle": "'Mesken Altı' Yasağı ve Tapu Kütüğü Regülasyonları",
          "text": "İkinci el motorlu kara taşıtı ticareti yapmak maksadıyla iş yeri kiralayacak veya satın alacak bir işletmecinin dikkat etmesi gereken en kritik husus, mutlak surette uygulanan 'mesken altı yasağı'dır. Bakanlık mevzuatına göre, parsel kullanım fonksiyonu imar planlarında 'konut alanı' olarak tahsis edilmiş yerlerdeki yapılarda hiçbir surette oto galeri açılamaz ve bu işletmelere çalışma ruhsatı verilemez. İlgili işletmenin açılabilmesi için binanın bulunduğu parselin imar planında mutlak surette 'ticaret' veya 'karma kullanım' fonksiyonuna sahip olması gerekmektedir.\n\nBu kuralın detaylandırılmış hali Tapu Kütüğü kayıtlarında gizlidir. Planlı Alanlar İmar Yönetmeliği kapsamında, eczane, fırın, kuaför veya berber gibi günlük yaşam ihtiyaçlarına yönelik ve gürültü/kirlilik üretmeyen hizmet kolları, konut alanlarının zemin katlarında özel izinlerle açılabilirken, ikinci el araç ticareti bu istisnai kapsamın tamamen dışında bırakılmıştır. İşyeri Açma ve Çalışma Ruhsatlarına İlişkin Yönetmelik (Ek 2/C, Madde 8) çok net bir kural koyar: Oto galerinin faaliyet göstereceği yapının tapu kütüğünde, 'mesken' (konut) olarak tescil edilmiş tek bir bağımsız bölüm dahi bulunmamalıdır. Binanın zemin katı 'dükkan' veya 'mağaza' niteliğinde olsa bile, üst katlarda mesken statüsünde daireler varsa, o binada oto galeri işletilmesine müsaade edilmemektedir. Ayrıca, faaliyet gösterilecek bağımsız bölümün tapuda açıkça dükkân, mağaza, ofis veya büro niteliğinde tescilli olması şart koşulmuştur."
        },
        {
          "subtitle": "Üçüncü Sınıf Gayrisıhhi Müesseseler İçin Fiziki Mimari Şartlar",
          "text": "Hukuki olarak 'Üçüncü Sınıf Gayrisıhhi Müesseseler' statüsünde sınıflandırılan ikinci el oto galeri iş yerleri, ruhsat alabilmek için İşyeri Açma ve Çalışma Ruhsatlarına İlişkin Yönetmeliğin 8.14 maddesinde belirtilen detaylı iç mimari ve fiziksel kapasite koşullarını harfiyen yerine getirmek mecburiyetindedir.\n\nBu fiziksel gereksinimlerin en başında alan büyüklüğü gelmektedir. Tek bir tacir veya esnaf tarafından işletilecek olan bir oto galerinin kapalı ve açık faaliyet alanlarının toplamı en az 80 metrekare olmak zorundadır. Bu 80 metrekarelik alanın da en az 60 metrekarelik bölümü, idari ofislerden veya bekleme alanlarından izole edilerek doğrudan araç teşhir ve sergileme alanı olarak planlanmalıdır. Regülasyonlar, sektörde maliyet paylaşımını teşvik etmek amacıyla 'ortak iş yeri' kavramına da müsaade etmektedir. Aynı iş yeri adresi içerisinde en fazla iki farklı tacirin faaliyet göstermesine izin verilmektedir; ancak bu senaryoda asgari alan gereksinimleri iki katına çıkmakta, toplam alanın en az 160 metrekare, teşhir alanının ise en az 120 metrekare olması şart koşulmaktadır.\n\nAraçların sergilendiği teşhir alanlarının net tavan yüksekliğinin en az 3 metre olması zorunludur. Bu gereksinim yalnızca mekansal bir ferahlık sağlamak için değil, aynı zamanda kapalı alanlardaki egzoz emisyon tahliyesini kolaylaştırmak ve olası karbonmonoksit birikimini engellemek için getirilmiş hayati bir iş sağlığı standardıdır."
        },
        {
          "subtitle": "LPG Yasağı ve Kaldırım İşgalleri",
          "text": "Güvenlik bağlamındaki en katı kural ise yakıt tipleriyle ilgilidir. Sıvılaştırılmış petrol gazı (LPG) veya sıkıştırılmış/sıvılaştırılmış doğal gaz (CNG/LNG) ile çalışan motorlu kara taşıtlarının, kapalı teşhir alanlarında sergilenmesi, depolanması veya muhafaza edilmesi infilak riski sebebiyle kesinlikle yasaktır. Bu tip alternatif yakıtlı araçların alım-satımını yapacak işletmelerin, ana binaya entegre ancak kapalı alanın dışında yer alan özel bir açık hava sergileme alanına sahip olmaları zorunludur.\n\nAyrıca, geçmişte çok sık rastlanan ve yaya trafiğini felç eden kaldırım işgalleri tamamen yasaklanmıştır. Motorlu araçlar, tahsis edilen 80 metrekarelik sınırların dışında, kamusal yollarda, kaldırımlarda veya ana gayrimenkulün ortak kullanım alanlarında (örneğin apartman otoparkı veya bina bahçesi) sergilenemez. İşletmenin ofis bölümü, müşteri kabul salonu ve teşhir alanı hukuken ve fiziken tek bir adreste birleşik olmalı, ayrıca personel ve müşteriler için standartlara uygun bir tuvalet (lavabo) alanı bulunmalıdır. İşletmenin mimari planı (iş yeri krokisi), giriş-çıkış kapılarının acil durumlarda hızlı tahliyeye imkan verecek genişlikte olduğunu kanıtlayacak şekilde çizilmeli ve belediyeye sunulmalıdır. İş yerinde ikinci el motorlu kara taşıtı ticareti haricinde başka hiçbir ticari faaliyet yürütülemez; yani aynı mekanda hem galericilik hem de emlakçılık yapılması dönemi hukuken kapanmıştır."
        },
        {
          "subtitle": "Toplu İş Yerleri ve Açık Alan İkinci El Araç Pazarları",
          "text": "Devletin temel stratejisi, münferit sokak arası galerilerindense, sektörel entegrasyonu sağlayan 'toplu iş yerlerini' ve galericiler sitelerini teşvik etmektir. İzmir Buca'daki Otokent Galericiler Sitesi ve Otonomi gibi devasa kompleksler, tüm bu fiziksel, hukuki ve çevresel gereksinimleri doğuştan karşılayan modern ticaret üsleri olarak tasarlanmıştır.\n\nMüstakil kapalı galerilerin ötesinde, açık havada faaliyet gösteren İkinci El Motorlu Kara Taşıtı Pazarları ise mevzuatta 'İkinci Sınıf Gayrisıhhi Müesseseler' olarak çok daha büyük bir ölçekte değerlendirilmektedir. Bu pazarların kurulabilmesi için, nüfusu 10.000'in altındaki yerleşim birimlerinde en az 5.000 metrekare, nüfusu 10.000'i aşan yerleşim birimlerinde ise en az 10.000 metrekarelik devasa arazilere ihtiyaç vardır. Bu alanların zeminlerinin asgari beton veya asfalt kaplı olması; bünyelerinde yangın söndürme altyapısı, anons sistemi, kadın/erkek ayrı ibadethaneler, zabıta bürosu, oto yıkama ünitesi, otopark, aydınlatma ve engelli erişim donatıları barındırması yasal bir zorunluluktur. Trafik yükünün yönetimi amacıyla pazarın büyüklüğüne göre en az 3 ila 5 adet bağımsız giriş-çıkış kapısı inşa edilmelidir."
        }
      ]
    },
    {
      "type": "step",
      "title": "Adım 14: Mesleki Yeterlilik (MYK Seviye 5) ve İnsan Kaynakları Standartları",
      "content": "Fiziki şartları ve imar kurallarını yerine getiren bir yatırımcının, ticari faaliyete başlayabilmesi için bizzat mesleki yeterliliğini devlet nezdinde kanıtlaması gerekmektedir. İkinci el motorlu kara taşıtı ticareti yetki belgesi başvurularının öncelikli ve vazgeçilemez koşulu, işletmeyi temsil ve ilzama yetkili yöneticinin veya şahıs firması sahibinin Mesleki Yeterlilik Kurumu (MYK) onaylı 'Motorlu Kara Taşıtları Alım Satım Sorumlusu (Seviye 5)' mesleki yeterlilik belgesini hak etmiş olmasıdır.",
      "subsections": [
        {
          "subtitle": "Eğitim, Sınav Süreci ve İstisnalar",
          "text": "Bu kritik belge, MYK tarafından sıkı denetimler sonucunda yetkilendirilmiş sınav ve belgelendirme kuruluşları aracılığıyla verilmektedir. Sınav süreci iki ana aşamadan oluşur: Otomotiv mevzuatı, tüketici koruma kanunu, faturalandırma ve iş sağlığı/güvenliği teorilerini ölçen yazılı test ve doğrudan araç başında ekspertiz yeteneğini, müşteri iletişimini ve fiyatlama senaryolarını test eden uygulamalı performans sınavı. Adayların belgeyi alabilmesi için her iki aşamayı da başarıyla tamamlaması gerekmektedir, ki bu süreç ortalama 10 günlük bir prosedürü kapsar.\n\nEğitim şartları konusunda sektörü rahatlatan devrim niteliğinde bir adım, 29 Nisan 2026 tarihli mevzuat değişikliği ile atılmıştır. Bu tarihten önce uygulanan ve ciddi mağduriyetlere yol açan 'en az lise mezunu olma' şartı yürürlükten kaldırılmış olup, asgari ilköğretim (ilkokul) diplomasına sahip olmak başvuru için yeterli hale getirilmiştir. Bununla birlikte, sektörde uzun yıllardır faaliyet gösterenlerin haklarını korumak amacıyla bir istisna tanınmış; 15 Ağustos 2020 tarihi itibarıyla gelir/kurumlar vergisi mükellefiyeti veya meslek odası kaydı bulunan işletmeciler bu öğrenim şartından tamamen muaf tutulmuştur.\n\nMesleki yeterlilik sadece sınav başarısıyla değil, etik ve hukuki bir geçmişle de desteklenmelidir. Adayların adli sicil kayıtlarının şeffaf olması, kasten işlenmiş suçlardan ötürü belirli bir sürenin üzerinde hapis cezası almamış olmaları şarttır. İflas geçmişi olan girişimcilerin yetki belgesi başvurusu yapabilmesi için ise, 2004 sayılı İcra ve İflas Kanunu hükümlerine göre itibarlarının hukuken iade edilmiş olması (iade-i itibar kararı) gerekmektedir."
        }
      ]
    },
    {
      "type": "step",
      "title": "Adım 15: İETTS Sistemi, Yetki Belgesi ve Bürokratik Müracaat Süreçleri",
      "content": "Fiziki ruhsatlandırma, vergi kayıtları ve MYK sertifikasyon süreçleri tamamlandıktan sonra nihai aşama, Ticaret Bakanlığı İl Müdürlükleri tarafından verilen 'İkinci El Motorlu Kara Taşıtı Ticareti Yetki Belgesi'nin alınmasıdır. Bu belge olmadan, noterlerde ticari amaçlı araç devir işlemi gerçekleştirilmesi sistem tarafından anında bloke edilmektedir.",
      "subsections": [
        {
          "subtitle": "İETTS Online Başvuru ve Evrak Seti",
          "text": "Başvurular, eski tip kağıt evrak teslimi ile değil, doğrudan e-Devlet kapısı ile entegre çalışan İkinci El Motorlu Kara Taşıtı Ticareti Bilgi Sistemi (İETTS - ietts.ticaret.gov.tr) isimli merkezi dijital portal üzerinden online olarak gerçekleştirilmek zorundadır. Başvuru esnasında sisteme yüklenmesi gereken evrak seti şu şekildedir:\n\n1. Oda Kayıt Belgesi (Esnaf veya Ticaret Odasından alınmış güncel faaliyet belgesi).\n2. Vergi Levhası Fotokopisi (Aktif ve güncel).\n3. Kimlik Fotokopisi.\n4. Öğrenim Durumunu Gösterir Belge (En az ilköğretim diploması veya mezuniyet belgesi).\n5. Motorlu Kara Taşıtları Alım Satım Sorumlusu Seviye 5 Mesleki Yeterlilik Belgesi.\n6. Tüzel kişilik başvurularında (Limited/Anonim Şirket), belge sahibi yöneticinin şirketi temsil ve ilzama yetkili olduğunu ispatlayan Ticaret Sicil onaylı İmza Sirküleri.\n7. Adli Sicil Belgesi (Sabıka Kaydı - e-Devlet üzerinden karekodlu alınabilir).\n8. İşyeri Açma ve Çalışma Ruhsatı.\n9. Yetki Belgesi Harcı Ödeme Makbuzu.\n10. İşyerinin satışa sunduğu veya mülkiyetinde bulunan araçların üçüncü şahıslara ve çevreye verebileceği zararları güvence altına alan 'Mali Sorumluluk Sigorta Poliçesi'.\n\nMüdürlük uzmanları tarafından yapılan ön inceleme ve iş yeri adresinde gerçekleştirilen fiziki denetimlerin ardından yetki belgesi onaylanmakta ve tüm bildirimler kayıtlı elektronik posta (KEP) veya standart e-posta adresleri üzerinden işletmeye tebliğ edilmektedir."
        },
        {
          "subtitle": "2026 Yılı Güncel Yetki Belgesi Harç Yapısı",
          "text": "Sektörde yaşanan bir diğer önemli değişiklik ise mali yükümlülükler kısmında gerçekleşmiştir. Önceki mevzuat dönemlerinde tamamen ücretsiz olan yetki belgesi başvuruları, 2026 yılında yürürlüğe konan düzenlemeler ile birlikte yüksek tutarlı bir yıllık harç sistemine bağlanmıştır. Bu harç ödemeleri, başvurudan önce doğrudan Vergi Dairesine veya Dijital Vergi Dairesi üzerinden gerçekleştirilip, resmi tahsilat makbuzunun İETTS sistemine beyan edilmesi suretiyle tamamlanmaktadır.\n\nHarç tutarları, demografik ve idari yoğunluğa göre kademelendirilmiştir:\n- Nüfusu 30.000'in Altında Olan Büyükşehir İlçeleri: 20.000 TL\n- Büyükşehir Statüsünde Olmayan İller (Anadolu Şehirleri): 20.000 TL\n- Büyükşehir Belediyesi Sınırları ve Metropol İlçeler: 40.000 TL\n\nBu kademeli harç sisteminin temel felsefesi, sektörel bariyerleri yükselterek, oto galericiliğini sadece 'ek iş' veya 'fırsatçılık' olarak gören yetersiz aktörlerin piyasaya girişini mali olarak caydırmaktır."
        }
      ]
    },
    {
      "type": "step",
      "title": "Adım 16: İşletme Sermayesi, Finansman Modelleri ve Kredi Regülasyonları",
      "content": "Oto galeri açmak, hukuki bariyerlerin ötesinde olağanüstü bir finansal planlama ve likidite yönetimi gerektirir. 'Araç alım satımı' eylemi, özünde yüksek hacimli nakdin sürekli devir daim ettiği bir finansman operasyonudur. Sektör analistleri ve MYK Galeri Belgesi danışmanlık kuruluşlarının 2026 yılı güncel verilerine göre, modern ve asgari şartları sağlayan bir oto galerinin kuruluş maliyeti yaklaşık 1.700.000 TL bandında seyretmektedir.",
      "subsections": [
        {
          "subtitle": "BDDK Makro İhtiyati Tedbirleri ve İkinci El Taşıt Kredileri",
          "text": "Oto galerilerin araç stok devir hızını (bir aracın ortalama satılma süresini) belirleyen en yaşamsal faktör, nihai tüketicinin otomobil kredilerine erişim imkanıdır. Türkiye Cumhuriyet Merkez Bankası'nın (TCMB) sıkı para politikaları ve Bankacılık Düzenleme ve Denetleme Kurumu'nun (BDDK) makro ihtiyati tedbirleri, doğrudan galerilerin satış hacimlerini dikte etmektedir.\n\nBDDK, ikinci el taşıt kredilerinde tüketiciyi aşırı borçlanmadan korumak ve piyasadaki suni talebi kırmak amacıyla Kredi Değer Oranı (Loan-to-Value) ve vade kısıtlamaları uygulamaktadır. Güncel kurallara göre bankalar, kasko değeri veya rayiç bedeli üzerinden taşıt kredisi kullandırırken çok net sınırlar çizmiştir:\n\nFiyat Baremleri ve Kredi Oranları:\nDeğeri 700.000 TL ve altında olan nispeten ekonomik araçlar için, aracın değerinin en fazla %50'si oranında (Örn: 700.000 TL'lik araç için maks. 350.000 TL) kredi kullandırılmaktadır.\n\nDeğeri 700.000 TL ile 1.100.000 TL arasında olan araçlar için bu oran hızla düşmekte, kredi limiti aracın değerinin ancak %30'una (Örn: 1.1M TL'lik araç için maks. 330.000 TL) tekabül etmektedir.\n\nDeğeri 1.100.000 TL'yi aşan (örneğin 2.100.000 TL değerindeki) orta-üst ve premium araçlar için kredi muslukları neredeyse tamamen kapanmakta, kredi çekilebilecek meblağ aracın değerine oranla çok marjinal seviyelere (maksimum 245.000 TL) gerilemektedir.\n\nVade ve Yaş Sınırları: İkinci el taşıt kredilerinde azami vade, alt segmentte 48 ay ile sınırlandırılmış olup, taşıtın değeri arttıkça bu vade 36, 24 ve 12 aya kadar düşürülmektedir. Ayrıca, bankaların kredi tahsis politikalarına göre krediye konu edilecek ikinci el araçlarda katı bir yaş sınırı uygulanmakta; en fazla 8 yaşına kadar olan taşıtlar kredilendirilebilmektedir. Kredi faiz oranlarının aylık %3,84 seviyelerinde seyrettiği ve ortalama 500 TL tahsis ücretlerinin eklendiği bir konjonktürde, oto galerilerin envanter alım stratejilerini revize etmeleri kaçınılmazdır. Kurumsal bir galeri, sermayesini yavaş devreden 10 yaş üstü araçlar yerine, BDDK kredilerine uygun, 8 yaş altı ve 700.000 - 1.100.000 TL bandındaki araçlara yatırarak likidite krizlerinden korunabilmektedir."
        }
      ],
      "table": {
        "headers": ["Maliyet Kalemi / Harcama Türü", "Açıklama ve Detaylar", "Tahmini Ortalama Tutar"],
        "rows": [
          ["Dükkan Kirası ve Depozito", "Metropollerde 80m² asgari ticari alanın ilk ay kirası ve yasal teminatı (10.000 - 50.000 TL arası değişken)", "20.000 TL (Minimum)"],
          ["MYK Seviye 5 Belge Ücreti", "Eğitim, yetkili kuruma ödenen sınav ve sertifikasyon harcı", "14.500 TL"],
          ["Meslek Odası ve Şirket Kuruluşu", "Ticaret odası veya esnaf odası kayıt harçları, mali müşavirlik açılış masrafları", "7.000 TL"],
          ["Ofis ve Güvenlik Altyapısı", "Müşteri bekleme salonu, masalar, bilgisayar, yazıcı, 7/24 kayıt yapabilen gece görüşlü güvenlik kamera sistemleri", "80.000 TL"],
          ["Dijital İlan Platformu Üyeliği", "Sahibinden.com, Arabam.com gibi sitelerde kurumsal mağaza aktivasyon bedelleri", "16.000 TL"],
          ["Yetki Belgesi Harcı (Devlet)", "Büyükşehir sınırları içerisinde yer alan işletmeler için uygulanan güncel tarife", "40.000 TL"],
          ["Başlangıç Araç Envanteri", "Stokta bulunması gereken, adet fiyatı ortalama 500.000 TL olan 3 adet alt-orta segment ikinci el otomobil", "1.500.000 TL"],
          ["TOPLAM ASGARİ SERMAYE İHTİYACI", "Operasyonlara sorunsuz bir şekilde başlayabilmek için gereken tahmini asgari bütçe", "~1.677.500 TL"]
        ]
      }
    },
    {
      "type": "step",
      "title": "Adım 17: Operasyonel Regülasyonlar ve Tüketici Hakları Çerçevesi",
      "content": "Oto galeri açılış sürecinin tamamlanması, yasal yükümlülüklerin bittiği değil, aksine başladığı andır. Ticaret Bakanlığı'nın regülasyonları, galericileri sıradan bir aracı olmaktan çıkarıp, sattığı ürünün arkasında durmak zorunda olan yasal bir garantör konumuna yerleştirmiştir. Bu durum, piyasadaki asimetrik bilgi problemini (satıcının aracın kusurlarını bilip, alıcının bilmemesi durumu) tüketici lehine çözmeyi amaçlar.",
      "subsections": [
        {
          "subtitle": "Zorunlu Ekspertiz Raporlaması ve İstisnalar",
          "text": "Yetki belgesine sahip bir oto galeri, işletme envanterinde bulunan bir aracı nihai tüketiciye satmadan hemen önce (satış işleminden azami 3 gün önce), Türk Standardları Enstitüsü (TSE) hizmet yeterlilik belgesine sahip bağımsız bir oto ekspertiz merkezinden detaylı bir ekspertiz raporu almak zorundadır. Aracın motor performansını, kaporta boya durumunu, şasi bütünlüğünü ve elektronik aksamını belgeleyen bu raporun ıslak imzalı veya e-imzalı bir kopyası, noterlikteki devir işlemleri esnasında notere ibraz edilmek ve sisteme işlenmek mecburiyetindedir.\n\nBu zorunluluk mutlak değildir; yasa koyucu, ömrünü tamamlamış yorgun araçlarda ekspertiz maliyetinin mantıksız olacağını öngörerek net bir istisna getirmiştir. Şayet satışa konu olan ikinci el motorlu kara taşıtı 8 yaşın üzerinde ise VEYA aracın kilometresi 160.000 kilometreyi aşmış durumdaysa, oto galeri zorunlu ekspertiz raporu almaktan ve notere ibraz etmekten yasal olarak muaf tutulmaktadır."
        },
        {
          "subtitle": "Yasal Garanti Yükümlülüğü ve Kapsamı",
          "text": "Oto galeriden araç satın alan bir tüketiciyi, doğrudan şahıstan araç alan bir tüketiciye göre devasa bir avantajla donatan en büyük regülasyon 'Garanti Zorunluluğu'dur. Yönetmelik uyarınca, yetki belgeli bir galeri tarafından satılan ikinci el araçlar, satış tarihinden itibaren 6 ay veya 6.000 kilometre (hangisi önce dolarsa) boyunca işletmenin yasal garantisi altındadır.\n\nBu garanti, aracın kozmetik kusurlarını (çizik, döşeme yırtığı) veya periyodik bakım parçalarını (fren balatası, filtreler vb.) değil, aracın hareketini ve güvenliğini sağlayan ana mekanik/elektronik donanımları kapsar. İkinci el araç garanti kapsamına giren kritik parçalar şunlardır:\n\n- Motor (Motor bloğu, pistonlar, silindir kapağı).\n- Şanzıman (Vites kutusu dişlileri, mekatronik ünite).\n- Tork Konvertörü.\n- Diferansiyel ve aktarma organları.\n- Aracın genel elektrik sistemi.\n\nEğer aracın satışı sonrasında, belirtilen süre ve kilometre sınırları içerisinde bu parçalardan herhangi birinde olağan dışı bir arıza meydana gelirse (ve arızanın tüketicinin hor kullanımından kaynaklanmadığı tespit edilirse), aracı satan galeri işletmesi söz konusu arızayı hiçbir ücret talep etmeksizin azami 3 ay (90 gün) içerisinde tamir ettirmekle veya tamir masraflarını karşılamakla yükümlüdür. Bu ağır maddi sorumluluk, galerilerin pert kayıtlı, ağır hasar görmüş veya motoru tükenmiş araçları ('toplama araçlar') satın alıp makyajlayarak satma pratiğini fiilen bitirmiş; sektörü daha kaliteli ve ekspertiz geçmişi temiz araçları portföye katmaya zorlamıştır."
        },
        {
          "subtitle": "Piyasa Müdahale Araçları: '6 Ay ve 6 Bin Kilometre' Kısıtlaması",
          "text": "Otomotiv piyasasında yaşanan arz şokları, pandemi sonrası küresel çip krizi ve artan döviz kurları, sıfır kilometre araçların karaborsaya düşmesine neden olmuştur. Oto galerilerin, bayilerden sıfır kilometre araçları topluca satın alıp stoklayarak (hoarding), bu araçları liste fiyatının çok üzerinde rakamlara ikinci el piyasasında satmalarını engellemek amacıyla, Ticaret Bakanlığı dünya genelinde eşine az rastlanan, oldukça sert bir piyasa müdahale aracı olan '6 Ay ve 6 Bin Kilometre' kuralını ihdas etmiştir.\n\nSadece ikinci el motorlu kara taşıtı ticaretiyle iştigal eden yetkili işletmeleri, oto kiralama şirketlerini ve distribütörleri bağlayan bu kuralın özü şudur: İşletmeler, kendi adlarına ilk tescilini (ruhsatını) aldıkları motosiklet, otomobil ve arazi taşıtlarını, ilk tescil tarihinin üzerinden 6 ay geçmedikçe ve araç en az 6.000 kilometre yol yapmadıkça, ne doğrudan ne de dolaylı olarak tüketiciye pazarlayamaz veya satamazlar.\n\nNoterlik bilgi sistemi, aracın tescil tarihi ve kilometre bilgisini (TÜVTÜRK ve yetkili servis entegrasyonları üzerinden) kontrol ederek, bu iki şartı aynı anda sağlamayan araçların ticari işletmeler tarafından devredilmesini elektronik ortamda anında reddetmektedir. Kuralın çevresinden dolanmak amacıyla aracı garajda yatırıp sadece kilometre sayacını suni olarak artıran veya taşıtı bireysel şahıslar üzerine kaydırarak satmaya çalışan işletmeler, Bakanlık müfettişlerinin sıkı takibine alınmıştır.\n\nOtomotiv sektöründe fiyat istikrarını sağlamak, sıfır araçların gerçek tüketicilere (son kullanıcılara) ulaşmasını kolaylaştırmak ve adil bir piyasa yapısını güçlendirmek amacıyla alınan bu karar, piyasadaki dezenflasyonist sürece katkı sağlamak üzere sürekli olarak uzatılmaktadır. Son olarak Resmi Gazete'de yayımlanan Yönetmelik değişikliği ile, başlangıçta geçici olarak tasarlanan bu yasaklı sürenin vadesi 1 Temmuz 2026 tarihine kadar uzatılmıştır. Bu katı regülasyon, oto galerilerin 'sıfır araç spekülatörü' kimliğinden tamamen sıyrılıp, asli işlevleri olan gerçek ikinci el araç ticaretine odaklanmalarını yasal bir zorunluluk haline getirmiştir."
        }
      ]
    },
    {
      "type": "step",
      "title": "Adım 18: Finansal Teknoloji Entegrasyonu: Güvenli Ödeme Sistemi",
      "content": "Ticaret Bakanlığı ve Türkiye Noterler Birliği (TNB) iş birliğiyle hayata geçirilen en inovatif ve sektörün iş yapış şeklini kökünden değiştiren yenilik, 'Güvenli Ödeme Sistemi'dir. 27 Eylül 2024 tarihi itibarıyla, Türkiye sınırlarındaki tüm ikinci el motorlu kara taşıtı alım-satım işlemlerinde bu sistemin kullanımı yasal olarak zorunlu hale getirilmiştir.\n\nBu sistem, nakit para taşıma riskini, sahte para dolandırıcılığını ve noterde imza atıldıktan sonra alıcının parayı ödemeden kaçması (veya parayı ödedikten sonra satıcının imza atmaması) şeklindeki asimetrik güven problemlerini sıfıra indiren bir 'Emanet Hesabı' (Escrow) modelidir. Sistemin operasyonel mekanizması şu adımlarla çalışır:",
      "subsections": [
        {
          "subtitle": "Güvenli Ödeme İşlem Adımları",
          "text": "1. Satıcı Veri Girişi: Oto galeri yetkilisi, Noterler Birliği ile entegre çalışan bankasının veya ödeme kuruluşunun dijital sistemine giriş yapar. Sisteme; satılacak aracın plakası, şasi numarası, alıcının T.C. Kimlik veya Vergi Numarası ve üzerinde anlaşılan satış bedeli kuruşu kuruşuna kaydedilir.\n\n2. Referans Numarası Üretimi: Sistem, bu işlem için benzersiz bir referans (güvenlik) numarası üretir ve bu kodu alıcının cep telefonuna SMS veya e-posta yoluyla otomatik olarak iletir.\n\n3. Alıcı Onayı ve Bloke İşlemi: Alıcı, kendi bankasının mobil uygulaması üzerinden 'Güvenli Ödeme' sekmesine girerek bu referans numarasını tuşlar. Ekranda beliren satıcı, araç ve tutar bilgilerini onayladıktan sonra, taşıt bedelini sistemin yönlendirdiği özel bir takas (havuz) hesabına transfer eder. Para, ne alıcının kullanımındadır ne de henüz satıcıya geçmiştir; devlet güvencesiyle Araf'ta (havuzda) bloke edilir.\n\n4. Tescil ve Otomatik Para Transferi: Taraflar noter huzurunda buluşur ve satış sözleşmesine imzalar atılır. Noterlik sistemi üzerinden aracın ruhsat tescili alıcı üzerine geçtiği saniye, sistemler arası API entegrasyonu tetiklenir ve havuzda bloke bekleyen taşıt bedeli saliseler içerisinde otomatik olarak satıcı galerinin banka hesabına aktarılır. Bu sayede, hem taraflar arası yüzde yüz güven tesis edilmiş olur, hem de tüm araç satış bedelleri bankacılık sistemi üzerinden geçtiği için kayıt dışı para transferleri ve kara para aklama girişimleri engellenmiş, tam vergi şeffaflığı sağlanmış olur."
        }
      ]
    },
    {
      "type": "step",
      "title": "Adım 19: Dijital Pazarlama, Vitrin Stratejileri ve Gelecek Projeksiyonları",
      "content": "Fiziksel teşhir alanlarının kusursuzluğu kadar, günümüz tüketici alışkanlıkları ekseninde araçların dijital ilan platformlarında nasıl konumlandırıldığı da galerinin karlılığını doğrudan etkilemektedir. Tüketicilerin %90'ından fazlası, fiziki olarak bir oto galeriye adım atmadan aylar önce, pazar araştırmasını Sahibinden.com, Arabam.com gibi ana akım ilan platformları üzerinden yürütmektedir.",
      "subsections": [
        {
          "subtitle": "HTML Optimizasyonu ve İlan Fiyatı Sınırlamaları",
          "text": "Kurumsal bir imaj çizebilmek ve algı yönetimini optimize edebilmek için oto galerilerin bu platformlarda bireysel üyelikler yerine, yıllık ciddi maliyetlere (ortalama 16.000 TL ve üzeri) katlanarak 'Kurumsal Hesap' (Mağaza) statüsünde yer almaları gerekmektedir. Mustafa Alkan gibi dijital pazarlama uzmanlarının analizlerine göre, kurumsal ilan stratejisi sadece bir fotoğraf yüklemekten ibaret değildir:\n\nHTML Optimizasyonu ve Açıklama Disiplini: İlan açıklamalarının rengarenk, göz yoran, büyük puntolu karmaşık fontlardan arındırılması elzemdir. Bilgi verici, aracın bakım geçmişini, ekspertiz durumunu (boyalı/değişen parçalar) şeffafça ortaya koyan, güven telkin eden ve HTML formatının imkan tanıdığı kalın (bold) metinler ve renkli çerçevelerle hiyerarşik bir düzene oturtulmuş içerikler, alıcının karar verme sürecini hızlandırır.\n\nDetaylı Arama Vitrinleri (Doping Kullanımı): Platformların sunduğu 'Detaylı Arama Vitrini' gibi özel araçlar, standart aramalardan ziyade spesifik, niş ve yüksek katma değerli araçları (örneğin cabriolet spor otomobiller veya belirli bir premium donanım paketine sahip SUV'lar) hedefleyen alıcı kitlesine nokta atışı ulaşmak için stratejik olarak kullanılmalıdır.\n\nİlan Fiyatı Sınırlamaları ve Bakanlık Denetimi: Dijital pazarlama artık serbest piyasa anarşisinden çıkıp yasal sınırlara tabi olmuştur. Ticaret Bakanlığı'nın yönetmeliği uyarınca, ilan platformlarına girilen ikinci el araç satış fiyatları, ilgili markanın ve modelin sıfır kilometre (distribütör tavsiye edilen) perakende satış fiyatını kesinlikle aşamaz. Platform yönetimleri, girilen ilan fiyatlarını algoritmalar vasıtasıyla distribütör listeleriyle karşılaştırmakla ve bu kuralı ihlal ederek piyasa dengesini bozan ilanları derhal yayından kaldırarak, hesap sahiplerinin bilgilerini yüksek idari para cezaları uygulanmak üzere Ticaret Bakanlığı'na raporlamakla mükelleftir. Bu durum, galerilerin fiyatlama stratejilerini (pricing strategy) oluştururken sürekli olarak markaların güncel sıfır kilometre liste fiyatlarını monitör etmelerini gerektirmektedir."
        },
        {
          "subtitle": "Sonuç ve Gelecek Projeksiyonları",
          "text": "Bir oto galeri işletmesi kurmak ve sürdürülebilir bir şekilde yönetmek, 2018 öncesi dönemin 'al-sat' basitliğinden çok uzak, son derece sofistike bir ticari operasyona evrilmiştir. İşletmeciler, bir yandan 50.000 TL ila 500.000 TL arasında değişen şirket kurulum sermayelerini ve 1.700.000 TL'yi aşan asgari envanter maliyetlerini yönetecek finansal okuryazarlığa sahip olmalı, diğer yandan BDDK'nın kredi kısıtlamalarına göre (8 yaş altı ve belirli değer baremlerindeki araçlar) stok optimizasyonu yapmalıdır.\n\nFiziki olarak, Tapu Kütüğünde 'mesken' bulunmayan, minimum 80 metrekare alana, 3 metre tavan yüksekliğine sahip ticari gayrimenkuller seçilmeli; idari olarak ise MYK Seviye 5 sertifikasyonu, Ticaret Bakanlığı İETTS yetki belgesi ve güvenli ödeme sistemleri eksiksiz entegre edilmelidir. Ayrıca, satış sonrası süreçte motor, şanzıman ve elektronik sistemler için 6 ay/6000 km yasal garanti yükümlülüğünün üstlenilmesi, piyasa güvenilirliğinin temel teminatı haline gelmiştir. Bu sert regülasyonlar bütünü; sektörü merdiven altı aktörlerden arındırmakta, kurumsal sermayeyi ödüllendirmekte ve ikinci el motorlu kara taşıtı ticaretini, Türkiye ekonomisi içerisinde tam güvenli, kayıtlı ve prestijli bir ekosisteme dönüştürmektedir. Sektörde uzun vadeli başarı, salt araç satma yeteneğine değil, makroekonomik eğilimleri okuyabilme ve bu çok katmanlı hukuki mevzuata dinamik bir şekilde uyum sağlayabilme kapasitesine bağlıdır."
        }
      ]
    }
  ];

  // Append new steps to base sections
  guide.sections = [...baseSections, ...newSteps];
  // Increase minute count to reflect new length
  guide.minutes = 25;

  fs.writeFileSync(path, JSON.stringify(data, null, 2));
  console.log('Successfully expanded to 19 steps including ALL original text word-for-word!');
} else {
  console.log('Guide not found!');
}
