import urllib.request
import json
import time
import os
import ssl

out_dir = os.path.join(os.path.dirname(__file__), '../public/signs')
os.makedirs(out_dir, exist_ok=True)

sign_file_map = {
    'T-1':  'Turkey_road_sign_T-1a.svg',
    'T-2':  'Turkey_road_sign_T-1b.svg',
    'T-3':  'Turkey_road_sign_T-2a.svg',
    'T-4':  'Turkey_road_sign_T-2b.svg',
    'T-5':  'Turkey_road_sign_T-3a.svg',
    'T-6':  'Turkey_road_sign_T-3b.svg',
    'T-7':  'Turkey_road_sign_T-4a.svg',
    'T-8':  'Turkey_road_sign_T-4b.svg',
    'T-11': 'Turkey_road_sign_T-7.svg',
    'T-12': 'Turkey_road_sign_T-8.svg',
    'T-13': 'Turkey_road_sign_T-9.svg',
    'T-14': 'Turkey_road_sign_T-10.svg',
    'T-15': 'Turkey_road_sign_T-11.svg',
    'T-16': 'Turkey_road_sign_T-12.svg',
    'T-18': 'Turkey_road_sign_T-14a.svg',
    'T-19': 'Turkey_road_sign_T-14b.svg',
    'T-20': 'Turkey_road_sign_T-15.svg',
    'T-21': 'Turkey_road_sign_T-16.svg',
    'T-23': 'Turkey_road_sign_T-18.svg',
    'T-24': 'Turkey_road_sign_T-19.svg',
    'T-26': 'Turkey_road_sign_T-21.svg',
    'T-27': 'Turkey_road_sign_T-22a.svg',
    'T-28': 'Turkey_road_sign_T-23a.svg',
    'T-30': 'Turkey_road_sign_T-25.svg',
    'T-31': 'Turkey_road_sign_T-26.svg',
    
    'TT-1': 'Turkey_road_sign_B-2a.svg',
    'TT-2': 'Turkey_road_sign_B-3.svg',
    'TT-3': 'Turkey_road_sign_TT-1.svg',
    'TT-4': 'Turkey_road_sign_TT-2.svg',
    'TT-5': 'Turkey_road_sign_TT-3.svg',
    'TT-6': 'Turkey_road_sign_TT-4.svg',
    'TT-8': 'Turkey_road_sign_TT-5.svg',
    'TT-9': 'Turkey_road_sign_TT-6.svg',
    'TT-16':'Turkey_road_sign_TT-13.svg',
    'TT-21':'Turkey_road_sign_TT-16a.svg',
    'TT-22':'Turkey_road_sign_TT-17.svg',
    'TT-25':'Turkey_road_sign_TT-24.svg',
    'TT-26':'Turkey_road_sign_TT-25.svg',
    'TT-27':'Turkey_road_sign_TT-26a.svg',
    'TT-28':'Turkey_road_sign_TT-27.svg',
    'TT-30':'Turkey_road_sign_TT-30.svg',
    'TT-31':'Turkey_road_sign_TT-32.svg',
    'TT-32':'Turkey_road_sign_TT-34a.svg',
    'TT-34':'TR_road_sign_TT-35a.svg',
    'TT-35':'TR_road_sign_TT-35b.svg',
    'TT-36':'TR_road_sign_TT-35c.svg',
    'TT-39':'Turkey_road_sign_TT-35g.svg',
    
    'B-1':  'Turkey_road_sign_B-14a.svg',
    'B-2':  'Turkey_road_sign_B-14b.svg',
    'B-3':  'Turkey_road_sign_B-15.svg',
    'B-4':  'Turkey_road_sign_B-16.svg',
    'B-5':  'Turkey_road_sign_B-24.svg',
    'B-6':  'Turkey_road_sign_B-28.svg',
    'B-7':  'Turkey_road_sign_B-29.svg',
    
    'P-1':  'Turkey_road_sign_P-1.svg',
    'P-2':  'Turkey_road_sign_P-2.svg',
    'P-3':  'Turkey_road_sign_P-3a.svg',
    'P-4':  'Turkey_road_sign_P-3e.svg',
}

def get_image_url(filename):
    # Wikimedia API requires the filename without underscores in the title parameter, 
    # but actual title parameter can handle spaces.
    title = f"File:{filename.replace('_', ' ')}"
    url = f"https://commons.wikimedia.org/w/api.php?action=query&titles={urllib.parse.quote(title)}&prop=imageinfo&iiprop=url&format=json"
    req = urllib.request.Request(url, headers={'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)'})
    try:
        ctx = ssl.create_default_context()
        ctx.check_hostname = False
        ctx.verify_mode = ssl.CERT_NONE
        with urllib.request.urlopen(req, context=ctx) as response:
            data = json.loads(response.read().decode())
            pages = data.get('query', {}).get('pages', {})
            for page_id, page_info in pages.items():
                if 'imageinfo' in page_info:
                    return page_info['imageinfo'][0]['url']
    except Exception as e:
        print(f"API Error for {filename}: {e}")
    return None

def download_file(url, filepath):
    req = urllib.request.Request(url, headers={'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)'})
    try:
        ctx = ssl.create_default_context()
        ctx.check_hostname = False
        ctx.verify_mode = ssl.CERT_NONE
        with urllib.request.urlopen(req, context=ctx) as response:
            with open(filepath, 'wb') as f:
                f.write(response.read())
            return True
    except Exception as e:
        print(f"Download Error for {url}: {e}")
        return False

def main():
    for sign_id, wiki_filename in sign_file_map.items():
        filepath = os.path.join(out_dir, f"{sign_id}.svg")
        
        # Skip if file already exists and is likely a real SVG (real ones are usually > 1KB, fake ones were < 1KB)
        # Fake SVGs generated by me were very small.
        if os.path.exists(filepath):
            size = os.path.getsize(filepath)
            if size > 1200:
                print(f"Skipping {sign_id}, already downloaded (size: {size})")
                continue
            else:
                print(f"Re-downloading {sign_id} (current size: {size} is too small, likely fake)")
        
        print(f"Resolving URL for {sign_id}...")
        url = get_image_url(wiki_filename)
        if url:
            print(f"Downloading {sign_id} from {url}...")
            if download_file(url, filepath):
                print(f"Success: {sign_id}")
            else:
                print(f"Failed to download: {sign_id}")
        else:
            print(f"Failed to resolve URL for: {sign_id}")
            
        time.sleep(1.5) # Prevent rate limiting

if __name__ == '__main__':
    main()
